### ISSUE TITLE
Legion Slim5 16IRH8 - Adding Support

### ISSUE THREAD

**Issue by Miademora** [rango886/LegionFanEmbeddedController#2]
Hello, this is what i get on a Legion Slim5 16IRH8.

How would i debug this?
Do i need Visual Studio?
Or is 2023 Legion model outside your scope? 

i dont have a device to flash my bios back in case something happens :)

```
########################### Read Mode ###########################
FAN1 speed      0                         FAN2 speed      0

FAN1 curve        70,  85,  21,  80,  90,  24,  82,  99,  24,  94
FAN2 curve         0,   0,   0,   0,   0,   0,   0,   0,   0,   0
ACC  time          0,   0,   0,   0,   0,   0,   0,   0,   0,   0
DEC  time          0,   0,   0,   0,   0,   0,   0,   0,   0,   0
CPU  lower temp    0,   0,   0,   0,   0,   0,   0,   0,   0,   0
CPU  upper temp    0,   0,   0,   0,   0,   0,   0,   0,   0,   0
GPU  lower temp    0,   0,   0,   0,   0,   0,   0,   0,   0,   0
GPU  upper temp    0,   0,   0,   0,   0,   0,   0,   0,   0,   0
IC   lower temp    0,   0,   0,   0,   0,   0,   0,   0,   0,   0
IC   upper temp  255, 255, 255, 255, 255, 255, 255, 255, 255, 255

EC Firmware Ver  0                      EC Chip model    8227 v2
```

**Comment by rango886** [comment]
You need Visual Studio to debug this project.
2023 may not support, if you can flash your bios,you can have a try :)
I only have 2021Legion model.

**Comment by rango886** [comment]
https://github.com/johnfanv2/LenovoLegionLinux may support 2023 model

**Comment by Miademora** [comment]
"Currently fan control is not working for the following models. Other features, probably work:
Mostly of Legion gen 8 (2023)"

Doesnt look like it. Maybe ill try when i can free up some time.

Thanks for the answer.

**Comment by TalalMash** [comment]
Works well on my 2021 LENOVO Legion 5 15ACH6.
The best part is LegionFanControl has a known bluescreen issue due to outdated RwDrv.sys when unplugging USB devices during EC read. This software solves it with ring, thank you!.
